### ISSUE TITLE
ImportError: You must be root to use this library on linux.

### ISSUE THREAD

**Issue by coderGtm** [eeriemyxi/mechvibes-lite#1]
While I was trying your project casually for some inspiration, I could not get it working. My System is Ubuntu 22.04. The error I am is this:

```
Traceback (most recent call last):
  File "/home/gtm/Desktop/mechvibes-lite/__main__.py", line 102, in <module>
    keyboard.hook(on_hook)
  File "/home/gtm/.local/lib/python3.10/site-packages/keyboard/__init__.py", line 461, in hook
    append(callback)
  File "/home/gtm/.local/lib/python3.10/site-packages/keyboard/_generic.py", line 67, in add_handler
    self.start_if_necessary()
  File "/home/gtm/.local/lib/python3.10/site-packages/keyboard/_generic.py", line 35, in start_if_necessary
    self.init()
  File "/home/gtm/.local/lib/python3.10/site-packages/keyboard/__init__.py", line 196, in init
    _os_keyboard.init()
  File "/home/gtm/.local/lib/python3.10/site-packages/keyboard/_nixkeyboard.py", line 113, in init
    build_device()
  File "/home/gtm/.local/lib/python3.10/site-packages/keyboard/_nixkeyboard.py", line 109, in build_device
    ensure_root()
  File "/home/gtm/.local/lib/python3.10/site-packages/keyboard/_nixcommon.py", line 174, in ensure_root
    raise ImportError('You must be root to use this library on linux.')
ImportError: You must be root to use this library on linux.
```

Initially, I could not read the error as the screen kept getting cleared, so I commented this line in `print_started()`:
```
console_setup.clear_screen()
```

**Comment by eeriemyxi** [comment]
I am aware of this issue on Linux systems. It turns out that the library I am using for monitoring the keyboard works on Linux only if you run it as root user; this alone opens a can of worms to make it work. Firstly, Linux has two popular display servers Xorg and Wayland. Xorg does allow monitoring the keyboard without root access, so I can make it work if I go through Xorg's API documentation, which I eventually will. But I have not found any way of making it work without being a root user on Wayland, yet.

Even if you run it as root, your sound servers won't work, so there's that. You'll have to make certain configurations to let your sound server do its job on the root user account. I don't recommend running any script as root, unless it's very safely crafted (which I am never confident about mine) and trusted, so running as root is not going to be my solution to the Linux users.  I should probably publicly archive this project for the time being.

**Comment by coderGtm** [comment]
When I run it as root, I get another error which does not let it run. Strangely though, when I run it in the VS Code terminal with sudo, it works perfectly!

**Comment by eeriemyxi** [comment]
> Strangely though, when I run it in the VS Code terminal with sudo, it works perfectly!

Cool. I think VSC does something internally that makes your sound server work on root account. Because there are hardly any issues with anything else other than the sound server nagging if you run it as root.

I have found a solution to all this (working on implementing it soon). It requires you to make some permission changes, for which you'll need root access, but once done, you can run the program safely. But it leaves you vulnerable to keyboard attacks, so it is recommended to do the steps on a different account then run it from there.

**Comment by coderGtm** [comment]
Ohk. All the Best! Meanwhile, I think I found an easier solution [here](https://stackoverflow.com/a/62172376/12312757). Closing this...

**Comment by eeriemyxi** [comment]
> Ohk. All the Best! Meanwhile, I think I found an easier solution [here](https://stackoverflow.com/a/62172376/12312757). Closing this...

If you're working on a completely new program, rather than a translation of Mechvibes (Mechvibes is based on scancodes), then I'd say you can try it. 

However, I'll let you know that Pynput uses the X server API underneath, which can only provide you keycodes on Linux systems, so if your users use a non-standard keyboard layout (not QWERTY), the keys will not give their sound based on their physical location (you'll need scancodes for this), rather it will be based on where it is decided on software-level. Also, Pynput only works on Xorg.

**Comment by coderGtm** [comment]
Didn't knew that. Thanks for sharing! I was mainly thinking about implementing something like this in Yantra Launcher when I remembered that I once saw this repository from your profile. Was just trying for some inspiration. My implementation (if ever done), will most likely be on the Android Platform. Cheers!

**Comment by eeriemyxi** [comment]
> Didn't knew that. Thanks for sharing! I was mainly thinking about implementing something like this in Yantra Launcher when I remembered that I once saw this repository from your profile. Was just trying for some inspiration. My implementation (if ever done), will most likely be on the Android Platform. Cheers!

Almost all users on phone use QWERTY layout, so you don't really need to do something complex, having a list of key-value pairs where a key is a letter from the English alphabet and its linked value some audio data would do the trick (compare the list of characters before and after text change, then find the ones that are only in after-text-change list -- it's not always reliable though). Though it won't work for special keys, for those you could handle [key events](https://developer.android.com/reference/android/view/ViewGroup.html#dispatchKeyEvent%28android.view.KeyEvent%29).

**Comment by coderGtm** [comment]
Yeah certainly! I think relying entirely on Key Dispatch Event is a better option as you don't need to extract the new character every time, apart from the rift with special keys. Thanks though!

**Comment by eeriemyxi** [comment]
> Yeah certainly! I think relying entirely on Key Dispatch Event is a better option as you don't need to extract the new character every time, apart from the rift with special keys. Thanks though!

That event won't work for soft keyboards afaik, though if the user is using hardware keyboard, or emulating one, it could work.

**Comment by coderGtm** [comment]
Oh yes right!
